package uk.gov.dvsa.motr.web.analytics;

public enum DataLayerMessageId {
    TRADE_API_CLIENT_EXCEPTION,
    VRM_VALIDATION_ERROR,
    CHANNEL_SELECTION_VALIDATION_ERROR,
    EMAIL_VALIDATION_ERROR,
    PHONE_NUMBER_VALIDATION_ERROR,
    CODE_ALREADY_RESENT,
    CODE_INCORRECT_3_TIMES,
    INVALID_CONFIRMATION_CODE_MESSAGE,
    CONFIRMATION_CODE_DOESNT_EXIST_MESSAGE,
    VEHICLE_NOT_FOUND,
    VEHICLE_MOT_TEST_EXPIRED,
    VEHICLE_MOT_TEST_DUE,
    VEHICLE_ANNUAL_TEST_EXPIRED,
    VEHICLE_ANNUAL_TEST_DUE,
    ANNUAL_TEST_DATE_UNKNOWN
}
